services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn -c gunicorn.conf.py base.wsgi:application
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:14.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build: ./nginx
    volumes:
      - ./nginx/certificates:/etc/ssl/certs
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
  redis:
    image: redis:7.0
    restart: always
    ports:
      - 6379:6379
    command: bash -c "redis-server --bind 0.0.0.0 --port 6379 --requirepass admin"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  static_volume:
  media_volume:
  redis_data:
    driver: local
