services:
    web:
        build:
            context: ./app
            dockerfile: Dockerfile.prod
        command: gunicorn -c gunicorn.conf.py base.wsgi:application
        volumes:
            - static_volume:/home/app/web/staticfiles
            - media_volume:/home/app/web/mediafiles
        expose:
            - 8000
        env_file:
            - ./.env.prod
        depends_on:
            - db
    db:
        image: mongo
        env_file:
            - ./.env.prod
            - ./.env.prod.db
        environment:
            - AUTH=yes
            - MONGO_INITDB_ROOT_USERNAME=mongoadmin
            - MONGO_INITDB_ROOT_PASSWORD=mongoadmin
        ports:
            - 27017:27017

    nginx:
        build: ./nginx
        volumes:
            - ./nginx/certificates:/etc/ssl/certs
            - static_volume:/home/app/web/staticfiles
            - media_volume:/home/app/web/mediafiles
        ports:
            - 80:80
            - 443:443
        depends_on:
            - web

volumes:
    static_volume:
    media_volume:
