services:
    web:
        build: ./app
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./app/:/usr/src/app/
        ports:
            - 8000:8000
        env_file:
            - ./.env.dev
        depends_on:
            - db
            - redis
    db:
        image: postgres:14.5
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=url_shortener_dev
    celery:
        restart: always
        build:
            context: ./app
        command: celery -A base worker -l info
        volumes:
            - celery_data:/var/lib/celery/data/
        env_file:
        - ./.env.dev
        depends_on:
            - db
            - web
    redis:
        restart: always
        image: redis:6.2
        ports:
            - 6379:6379

volumes:
    postgres_data:
    celery_data:
