services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.prod
    command: gunicorn -c gunicorn.prod.conf.py base.asgi:application -k uvicorn.workers.UvicornWorker
    volumes:
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:14.5
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    volumes:
      - ./nginx/certificates:/etc/ssl/certs
      - static_volume:/home/app/web/staticfiles
      - media_volume:/home/app/web/mediafiles
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
  media_volume:
